In [1]:
# シーケンス + と *

In [2]:
l = [1,2,3]

In [3]:
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
5*'abcd'

'abcdabcdabcdabcdabcd'

In [5]:
[1,2,3] + [4,5]

[1, 2, 3, 4, 5]

In [6]:
board = [['_']*3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [7]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [8]:
weird_board = [['_']*3] *3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [9]:
weird_board[1][2]='0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [10]:
row = ['_'] * 3
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

In [11]:
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [12]:
board =[]
for i in range(3):
    row = ['_'] * 3
    board.append(row)

In [13]:
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [14]:
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [15]:
fruits=['grape','raspberry','apple','banana']

In [16]:
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [17]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [18]:
sorted(fruits,key=len)

['grape', 'apple', 'banana', 'raspberry']

In [19]:
sorted(fruits,key=len,reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [20]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [21]:
fruits.sort()

In [22]:
fruits

['apple', 'banana', 'grape', 'raspberry']

In [23]:
import array
numbers = array.array('h',[-2,-1,0,1,2])
memv = memoryview(numbers)
len(memv)

5

In [24]:
memv[0]

-2

In [25]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [26]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [27]:
#numpy
import numpy
a= numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
type(a)

numpy.ndarray

In [29]:
a.shape #次元１ 要素数12

(12,)

In [30]:
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.transpose() #転置

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [32]:
from collections import deque
dq = deque(range(10),maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [34]:
dq.rotate(-4)
dq


deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [35]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
dq.extend([11,22,33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [37]:
dq.extend([11,22,33,44,55])
dq

deque([8, 9, 11, 22, 33, 11, 22, 33, 44, 55])